apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  selector:
    app: vaultwarden-postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP