#!/bin/bash

echo "=== NPM Private Registry Setup ==="
echo ""
echo "Your private npm registry is available at: https://npm.gmac.io"
echo ""
echo "To use this registry:"
echo ""
echo "1. Set registry for your scope:"
echo "   npm config set @yourcompany:registry https://npm.gmac.io"
echo ""
echo "2. Login to the registry:"
echo "   npm login --registry https://npm.gmac.io --scope=@yourcompany"
echo ""
echo "3. Create a user (first time only):"
echo "   npm adduser --registry https://npm.gmac.io"
echo ""
echo "4. Publish packages:"
echo "   # In package.json: \"name\": \"@yourcompany/package-name\""
echo "   npm publish"
echo ""
echo "5. Install private packages:"
echo "   npm install @yourcompany/package-name"
echo ""
echo "Note: The web UI is protected by GitHub OAuth"
echo "      The npm CLI uses npm credentials"