apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-clickhouse-config
  namespace: plausible
data:
  custom.xml: |
    <clickhouse>
      <logger>
        <level>warning</level>
        <console>true</console>
      </logger>
      <listen_host>0.0.0.0</listen_host>
      <max_connections>4096</max_connections>
      <keep_alive_timeout>3</keep_alive_timeout>
      <max_concurrent_queries>100</max_concurrent_queries>
    </clickhouse>