apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: verdaccio-storage
  namespace: npm-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path