apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: auth-system
  labels:
    app: oauth2-proxy
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 4180
    targetPort: http
    protocol: TCP
  selector:
    app: oauth2-proxy
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800